### ISSUE TITLE
Another generic extension decompilation error similar to #298

### ISSUE THREAD

**Issue by beno-pete** [hazzik/DelegateDecompiler#303]
Similar to #298 just with another argument, error decompiling case without explicit type cast (event with 0.35.1):
Working properly with pre 0.35.

```
using DelegateDecompiler;
using System.Linq;

namespace ConsoleApp1;

static class Program
{
    static void Main()
    {
        var q = new Cls[0].AsQueryable();
        var a = DecompileExtensions.Decompile(q.Select(x => x.Ext1(0)));
        var b = DecompileExtensions.Decompile(q.Select(x => x.Ext2(0)));
    }

    [Computed]
    public static int Ext1<T>(this T value, int i) where T : Intf => ((Intf)value).Value(i);

    [Computed]
    public static int Ext2<T>(this T value, int i) where T : Intf => value.Value(i);

}

public interface Intf
{
    public int Value(int i) => i;
}

public class Cls : Intf
{
}
```

**Comment by beno-pete** [comment]
@hazzik looks like sometime oversimplification of test cases is not a good thing...
The former test code works with 0.35.2, but the actual production code isnt. 
Here is another test case that does not work event with 0.35.2, though it actually is basically same just with different arguments,
and it this case IsValidAt1 is ok but both IsValidAt2 and IsValidAt3 produce error (IsValidAt2 has interface as argument, IsValidAt3 has unused argument):

```
using DelegateDecompiler;
using System;
using System.Linq;

namespace ConsoleApp1;

static class Program
{
    static void Main()
    {
        var q = new Entity[0].AsQueryable();
        var p = new Provider();
        var a = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt1(DateTime.Now)));
        var b = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt2(p)));
        var c = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt3(DateTime.Now)));
    }

    [Computed]
    public static bool IsValidAt1<TEntity>(this TEntity entity, DateTime dateTime) where TEntity : ITimeValidity => entity.IsValidAt(dateTime);

    [Computed]
    public static bool IsValidAt2<TEntity>(this TEntity entity, IDateTimeProvider dateTimeProvider) where TEntity : ITimeValidity => entity.IsValidAt(dateTimeProvider.Now);

    [Computed]
    public static bool IsValidAt3<TEntity>(this TEntity entity, DateTime dateTime) where TEntity : ITimeValidity => entity.IsValidAt(DateTime.Now);

}

public interface IDateTimeProvider
{
    public DateTime Now => default;
}

public interface ITimeValidity
{
    public bool IsValidAt(DateTime time) => default;
}

public class Entity : ITimeValidity
{
}

public class Provider : IDateTimeProvider
{
}
```

```
System.NotSupportedException
  HResult=0x80131515
  Message=The IL opcode 'ldobj' is not supported by DelegateDecompiler. This opcode cannot be decompiled into an expression tree. Consider simplifying the method or using a different approach.
  Source=DelegateDecompiler
  StackTrace:
   at DelegateDecompiler.Processor.ProcessInstruction(ProcessorState state, Instruction instruction)
   ...
```

The error seems to be same as one with 0.35.0 in this case

Or should I create new issue for this?

**Comment by hazzik** [comment]
Does this work in 0.34.x? I might have lost `ldobj` support when rewrote processor.

**Comment by hazzik** [comment]
Also please create another issue, as seem different opcode.
