### ISSUE TITLE
Another case of generic extension decompilation errors

### ISSUE THREAD

**Issue by beno-pete** [hazzik/DelegateDecompiler#308]
Extracted from comment in #303
Here is another test case that does not work event with 0.35.2, though it actually is basically same just with different arguments,
and it this case IsValidAt1 is ok but all others produce error (IsValidAt2 has interface as argument, IsValidAt3 has unused argument, IsValid4 without argument):
And yes this is all working properly in 0.34.2 (found problems only after i upgraded to 0.35 and my project queries basically all broke)

```
using DelegateDecompiler;
using System;
using System.Linq;

namespace ConsoleApp1;

static class Program
{
    static void Main()
    {
        var q = new Entity[0].AsQueryable();
        var p = new Provider();
        var a = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt1(DateTime.Now)));
        var b = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt2(p)));
        var c = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt3(DateTime.Now)));
        var d = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt4()));
    }

    [Computed]
    public static bool IsValidAt1<TEntity>(this TEntity entity, DateTime dateTime) where TEntity : ITimeValidity => entity.IsValidAt(dateTime);

    [Computed]
    public static bool IsValidAt2<TEntity>(this TEntity entity, IDateTimeProvider dateTimeProvider) where TEntity : ITimeValidity => entity.IsValidAt(dateTimeProvider.Now);

    [Computed]
    public static bool IsValidAt3<TEntity>(this TEntity entity, DateTime dateTime) where TEntity : ITimeValidity => entity.IsValidAt(DateTime.Now);

    [Computed]
    public static bool IsValidAt4<TEntity>(this TEntity entity) where TEntity : ITimeValidity => entity.IsValidAt(DateTime.Now);

}

public interface IDateTimeProvider
{
    public DateTime Now => default;
}

public interface ITimeValidity
{
    public bool IsValidAt(DateTime time) => default;
}

public class Entity : ITimeValidity
{
}

public class Provider : IDateTimeProvider
{
}
```

```
System.NotSupportedException
  HResult=0x80131515
  Message=The IL opcode 'ldobj' is not supported by DelegateDecompiler. This opcode cannot be decompiled into an expression tree. Consider simplifying the method or using a different approach.
  Source=DelegateDecompiler
  StackTrace:
   at DelegateDecompiler.Processor.ProcessInstruction(ProcessorState state, Instruction instruction)
   ...
```

**Comment by beno-pete** [comment]
More cases this time in c#14/net10 syntax, nothing except first one works (including new static extensions):

```
using DelegateDecompiler;
using System;
using System.Linq;

namespace ConsoleApp1;

static class Program
{
    static void Main()
    {
        var q = new Entity[0].AsQueryable();
        var p = new Provider();
        var a = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt1(DateTime.Now)));
        var b = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt2(p)));
        var c = DecompileExtensions.Decompile(q.Where(x => x.IsValidAt3(DateTime.Now)));
        var d = DecompileExtensions.Decompile(q.Where(x => Entity.StaticExtIsValid1(x)));
        var e = DecompileExtensions.Decompile(q.Where(x => Entity.StaticExtIsValid2(x, p)));
        var f = DecompileExtensions.Decompile(q.Where(x => Entity.StaticExtIsValid2(x, p)));
    }

    extension<TEntity>(TEntity entity) where TEntity : ITimeValidity
    {
        [Computed]
        public bool IsValidAt1(DateTime dateTime) => entity.IsValidAt(dateTime);
        [Computed]
        public bool IsValidAt2(IDateTimeProvider dateTimeProvider) => entity.IsValidAt(dateTimeProvider.Now);
        [Computed]
        public bool IsValidAt3(DateTime dateTime) => entity.IsValidAt(DateTime.Now);

        [Computed]
        public static bool StaticExtIsValid1(TEntity x) => x.IsValidAt(DateTime.Now);
        [Computed]
        public static bool StaticExtIsValid2(TEntity x, IDateTimeProvider dateTimeProvider) => x.IsValidAt(dateTimeProvider.Now);
        [Computed]
        public static bool StaticExtIsValid3(TEntity x, DateTime dateTime) => x.IsValidAt(dateTime);
    }
}

public interface IDateTimeProvider
{
    public DateTime Now => default;
}

public interface ITimeValidity
{
    public bool IsValidAt(DateTime time) => default;
}

public class Entity : ITimeValidity
{
}

public class Provider : IDateTimeProvider
{
}
```

**Comment by hazzik** [comment]
Should be fixed in 0.35.3, please check

**Comment by beno-pete** [comment]
Everything seems to working, thx
